export const ADD_STAFF = 'ADD_STAFF';
export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFF_FAILED = 'STAFF_FAILED';
export const STAFF_LOADING = 'STAFF_LOADING'

export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING'